// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ARpcCaller.cs
#pragma warning disable 1591, 0612, 3021

#region Designer generated code

using System;
using System.Threading.Tasks;
using Nirge.Core;
using log4net;

namespace Nirge.Core {
  public class CARpcCaller : CRpcCaller {
    public CARpcCaller(CRpcCallerArgs args, ILog log, IRpcStream stream, IRpcTransfer transfer, IRpcCallStubProvider stubs)
    	: base(args, log, stream, transfer, stubs, global::Nirge.Core.AReflection.Descriptor.Services[0], 1) {}
    public void a(int channel = 0){
      Call<Nirge.Core.RpcCallArgsEmpty>(channel, 1, ArgsEmpty);
    }
    public void b(int channel = 0){
      Call<Nirge.Core.RpcCallArgsEmpty>(channel, 2, ArgsEmpty);
    }
    public void c(Nirge.Core.cargs args, int channel = 0){
      Call<Nirge.Core.cargs>(channel, 3, args);
    }
    public void d(Nirge.Core.dargs args, int channel = 0){
      Call<Nirge.Core.dargs>(channel, 4, args);
    }
    public Task<Nirge.Core.RpcCallArgsEmpty> e(int channel = 0){
      return CallAsync<Nirge.Core.RpcCallArgsEmpty, Nirge.Core.RpcCallArgsEmpty>(channel, 5, ArgsEmpty);
    }
    public Task<Nirge.Core.fret> f(int channel = 0){
      return CallAsync<Nirge.Core.RpcCallArgsEmpty, Nirge.Core.fret>(channel, 6, ArgsEmpty);
    }
    public Task<Nirge.Core.RpcCallArgsEmpty> g(Nirge.Core.gargs args, int channel = 0){
      return CallAsync<Nirge.Core.gargs, Nirge.Core.RpcCallArgsEmpty>(channel, 7, args);
    }
    public Task<Nirge.Core.hret> h(Nirge.Core.hargs args, int channel = 0){
      return CallAsync<Nirge.Core.hargs, Nirge.Core.hret>(channel, 8, args);
    }
  }
}

#endregion
