// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IBRpcService.cs
#pragma warning disable 1591, 0612, 3021

#region Designer generated code

using System;
using Nirge.Core;

namespace Nirge.Core {
  public interface IBRpcService : IRpcService {
    void a(int channel);
    void b(int channel);
    void c(int channel, Nirge.Core.cargs args);
    void d(int channel, Nirge.Core.dargs args);
    void e(int channel);
    Nirge.Core.fret f(int channel);
    void g(int channel, Nirge.Core.gargs args);
    Nirge.Core.hret h(int channel, Nirge.Core.hargs args);
  }
}

#endregion
